server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER
  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/durgeshp11898/Microservices-Config-Server
          clone-on-start: true